---
# tasks file for create-ec2

    - name: Create an EC2 instance
      ec2:
        key_name: "{{ ssh_key }}"
        instance_type: "{{ instance_size }}"
        region: '{{ region }}'
        group_id: '{{ sec_group }}'
        image: '{{ ami }}'
        wait: true
        vpc_subnet_id: '{{ subnet }}'
        volumes:
           - device_name: /dev/sda1
             volume_type: "{{ vol_type }}"
             volume_size: "{{ vol_size_gb }}"
             delete_on_termination: true
        assign_public_ip: yes
      register: ec2_output


    - name: Add variables for the newly created instance to appropriate file
      blockinfile:
        path: 'host_vars/{{ server }}.yml'
        create: yes
        content: |
              ansible_host: {{ my_ec2_server.private_ip }}
              ansible_user: {{ ami_user }}
              host_region: {{ my_ec2_server.region }}
              instance_type: {{ my_ec2_server.instance_type }}
              host_az: {{ my_ec2_server.placement }}
              host_os: {{ ami_os }}
              os_version: {{ ami_os_version }}
      with_items: '{{ ec2_output.instances }}'
      loop_control:
        loop_var: my_ec2_server

    - name: Add the newly created instance to inventory
      lineinfile:
        path: "{{ inventory_file_path }}"
        line: "{{ server }}"
    - name: Wait for a while before confirming the server is ready
      vars:
        ansible_connection: local
      wait_for: 
        port: 22
        host: '{{ item.private_ip }}'
        delay: 20
      with_items: '{{ ec2_output.instances }}'
